export const OPERATORS = {
    equal: '=',
    notEqual: '!=',
    greaterThan: '>',
    greaterThanOrEqual: '>=',
    lessThan: '<',
    lessThanOrEqual: '<=',
    like: '~',
    notLike: '!~',
    anyEqual: '?=',
    anyNotEqual: '?!=',
    anyGreaterThan: '?>',
    anyGreaterThanOrEqual: '?>=',
    anyLessThan: '?<',
    anyLessThanOrEqual: '?<=',
    anyLike: '?~',
    anyNotLike: '?!~',
} as const

export const DATETIME_MACROS = [
    '@now',
    '@second',
    '@minute',
    '@hour',
    '@weekday',
    '@day',
    '@month',
    '@year',
    '@yesterday',
    '@tomorrow',
    '@todayStart',
    '@todayEnd',
    '@monthStart',
    '@monthEnd',
    '@yearStart',
    '@yearEnd',
] as const
